version: '3.4'

services:
  clientsdb:
    image: postgres:latest

  productrecognitiondb:
    image: mongo:latest

  zookeeper:
    image: confluentinc/cp-zookeeper:latest

  kafka:
    image: confluentinc/cp-kafka:latest

  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Clients/Presentation/Clients.API/Dockerfile

  productrecognition.api:
    image: ${DOCKER_REGISTRY-}productrecognitionapi
    build:
      context: .
      dockerfile: ProductRecognition/Presentation/ProductRecognition.API/Dockerfile

  webapp:
    image: dockerimgek/webappprodtest:latest

volumes:
  postgres_data:
  mongo_data: