version: '3.4'

services:
  clientsdb:
    container_name: clientsdb
    environment:
      - POSTGRES_USER=pstgrsqluser
      - POSTGRES_PASSWORD=pstgrs3381
      - POSTGRES_DB=ClientsDB
    restart: always
    ports:
      - "7001:5432"
    volumes:
      - postgres_data_clients:/var/lib/postgresql/data

  productrecognitiondb:
    container_name: productrecognitiondb
    restart: always
    ports:
      - "7002:27017"
    volumes:
      - mongo_data:/data/db

  basketformationdb:
    container_name: basketformationdb
    environment:
      - POSTGRES_USER=pstgrsqluser
      - POSTGRES_PASSWORD=pstgrs3381
      - POSTGRES_DB=BasketFormationDB
    restart: always
    ports:
      - "7003:5432"
    volumes:
      - postgres_data_basketformation:/var/lib/postgresql/data

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - .data/zookeeper/data:/data
      - .data/zookeeper/datalog:/datalog

  kafka:
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:9092,LISTENER_DOCKER_EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10485760
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  clients.api:
    container_name: clients.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zUBHaFFxeT
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=192.168.0.109;Port=7001;Database=ClientsDB;User Id=pstgrsqluser;Password=pstgrs3381;"
    depends_on:
      - clientsdb
      - kafka
    ports:
      - "8001:443"
      - "8011:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  productrecognition.api:
    container_name: productrecognition.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8002
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zUBHaFFxeT
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=mongodb://productrecognitiondb:27017"
    depends_on:
      - productrecognitiondb
      - kafka
    ports:
      - "8002:443"
      - "8022:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  basketformation.api:
    container_name: basketformation.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8003
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zUBHaFFxeT
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=192.168.0.109;Port=7003;Database=BasketFormationDB;User Id=pstgrsqluser;Password=pstgrs3381;"
    depends_on:
      - basketformationdb
      - kafka
    ports:
      - "8003:443"
      - "8033:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro

  webapp:
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8004
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zUBHaFFxeT
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    depends_on:
      - kafka
    ports:
      - "8004:443"
      - "8044:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro