version: '3.4'

services:
  clientsdb:
    image: postgres:latest

  productrecognitiondb:
    image: mongo:latest

  basketformationdb:
    image: postgres:latest

  zookeeper:
    image: confluentinc/cp-zookeeper:latest

  kafka:
    image: confluentinc/cp-kafka:latest

  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Clients/Presentation/Clients.API/Dockerfile

  productrecognition.api:
    image: ${DOCKER_REGISTRY-}productrecognitionapi
    build:
      context: .
      dockerfile: ProductRecognition/Presentation/ProductRecognition.API/Dockerfile

  basketformation.api:
    image: ${DOCKER_REGISTRY-}basketformationapi
    build:
      context: .
      dockerfile: BasketFormation/Presentation/BasketFormation.API/Dockerfile

  webapp:
    image: dockerimgek/webappprodtest:latest

volumes:
  postgres_data_clients:
  postgres_data_basketformation:
  mongo_data: