version: '3.4'

services:
  clientsdb:
    container_name: clientsdb
    environment:
      - POSTGRES_USER=pstgrsqluser
      - POSTGRES_PASSWORD=pstgrs3381
      - POSTGRES_DB=ClientsDB
    restart: always
    ports:
      - "7001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clients.api:
    container_name: clients.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=zUBHaFFxeT
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - "DatabaseSettings:ConnectionString=Server=192.168.0.109;Port=7001;Database=ClientsDB;User Id=pstgrsqluser;Password=pstgrs3381;"
    depends_on:
      - clientsdb
    ports:
      - "8001:443"
      - "8011:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ~/.aspnet/https:/https:ro