version: '3.4'

services:
  clientsdb:
    image: postgres:latest

  zookeeper:
    image: confluentinc/cp-zookeeper:latest

  kafka:
    image: confluentinc/cp-kafka:latest

  clients.api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Clients/Presentation/Clients.API/Dockerfile

volumes:
  postgres_data: